package com.raulvintila.app.lieflashcards.Database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBCARD_CONTENT.
 */
public class DBCardContent {

    private Long id;
    private Long remoteId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String value;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String version;
    private long cardId;

    public DBCardContent() {
    }

    public DBCardContent(Long id) {
        this.id = id;
    }

    public DBCardContent(Long id, Long remoteId, String name, String value, String type, String version, long cardId) {
        this.id = id;
        this.remoteId = remoteId;
        this.name = name;
        this.value = value;
        this.type = type;
        this.version = version;
        this.cardId = cardId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(Long remoteId) {
        this.remoteId = remoteId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getVersion() {
        return version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVersion(String version) {
        this.version = version;
    }

    public long getCardId() {
        return cardId;
    }

    public void setCardId(long cardId) {
        this.cardId = cardId;
    }

}
