package com.raulvintila.app.lieflashcards.Database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBCARD_TAG.
 */
public class DBCardTag {

    private Long id;
    /** Not-null value. */
    private String text;
    private long cardId;

    public DBCardTag() {
    }

    public DBCardTag(Long id) {
        this.id = id;
    }

    public DBCardTag(Long id, String text, long cardId) {
        this.id = id;
        this.text = text;
        this.cardId = cardId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public long getCardId() {
        return cardId;
    }

    public void setCardId(long cardId) {
        this.cardId = cardId;
    }

}
