package com.raulvintila.app.lieflashcards.Database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.raulvintila.app.lieflashcards.Database.dao.DBCardProgress;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DBCARD_PROGRESS.
*/
public class DBCardProgressDao extends AbstractDao<DBCardProgress, Long> {

    public static final String TABLENAME = "DBCARD_PROGRESS";

    /**
     * Properties of entity DBCardProgress.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemoteId = new Property(1, Long.class, "remoteId", false, "REMOTE_ID");
        public final static Property CardId = new Property(2, int.class, "cardId", false, "CARD_ID");
        public final static Property Level = new Property(3, double.class, "level", false, "LEVEL");
        public final static Property Volatility = new Property(4, double.class, "volatility", false, "VOLATILITY");
        public final static Property LastStudyDate = new Property(5, Long.class, "lastStudyDate", false, "LAST_STUDY_DATE");
        public final static Property Version = new Property(6, String.class, "version", false, "VERSION");
        public final static Property TimesStudied = new Property(7, int.class, "timesStudied", false, "TIMES_STUDIED");
        public final static Property UserDeckId = new Property(8, long.class, "userDeckId", false, "USER_DECK_ID");
    };

    private Query<DBCardProgress> dBUserDeck_CardsProgressQuery;

    public DBCardProgressDao(DaoConfig config) {
        super(config);
    }
    
    public DBCardProgressDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DBCARD_PROGRESS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'REMOTE_ID' INTEGER UNIQUE ," + // 1: remoteId
                "'CARD_ID' INTEGER NOT NULL ," + // 2: cardId
                "'LEVEL' REAL NOT NULL ," + // 3: level
                "'VOLATILITY' REAL NOT NULL ," + // 4: volatility
                "'LAST_STUDY_DATE' INTEGER," + // 5: lastStudyDate
                "'VERSION' TEXT NOT NULL ," + // 6: version
                "'TIMES_STUDIED' INTEGER NOT NULL ," + // 7: timesStudied
                "'USER_DECK_ID' INTEGER NOT NULL );"); // 8: userDeckId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBCARD_PROGRESS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBCardProgress entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindLong(2, remoteId);
        }
        stmt.bindLong(3, entity.getCardId());
        stmt.bindDouble(4, entity.getLevel());
        stmt.bindDouble(5, entity.getVolatility());
 
        Long lastStudyDate = entity.getLastStudyDate();
        if (lastStudyDate != null) {
            stmt.bindLong(6, lastStudyDate);
        }
        stmt.bindString(7, entity.getVersion());
        stmt.bindLong(8, entity.getTimesStudied());
        stmt.bindLong(9, entity.getUserDeckId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBCardProgress readEntity(Cursor cursor, int offset) {
        DBCardProgress entity = new DBCardProgress( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // remoteId
            cursor.getInt(offset + 2), // cardId
            cursor.getDouble(offset + 3), // level
            cursor.getDouble(offset + 4), // volatility
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // lastStudyDate
            cursor.getString(offset + 6), // version
            cursor.getInt(offset + 7), // timesStudied
            cursor.getLong(offset + 8) // userDeckId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBCardProgress entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemoteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCardId(cursor.getInt(offset + 2));
        entity.setLevel(cursor.getDouble(offset + 3));
        entity.setVolatility(cursor.getDouble(offset + 4));
        entity.setLastStudyDate(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setVersion(cursor.getString(offset + 6));
        entity.setTimesStudied(cursor.getInt(offset + 7));
        entity.setUserDeckId(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBCardProgress entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBCardProgress entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "cardsProgress" to-many relationship of DBUserDeck. */
    public List<DBCardProgress> _queryDBUserDeck_CardsProgress(long userDeckId) {
        synchronized (this) {
            if (dBUserDeck_CardsProgressQuery == null) {
                QueryBuilder<DBCardProgress> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserDeckId.eq(null));
                dBUserDeck_CardsProgressQuery = queryBuilder.build();
            }
        }
        Query<DBCardProgress> query = dBUserDeck_CardsProgressQuery.forCurrentThread();
        query.setParameter(0, userDeckId);
        return query.list();
    }

}
