package com.raulvintila.app.lieflashcards.Database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.raulvintila.app.lieflashcards.Database.dao.DBCard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DBCARD.
*/
public class DBCardDao extends AbstractDao<DBCard, Long> {

    public static final String TABLENAME = "DBCARD";

    /**
     * Properties of entity DBCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemoteId = new Property(1, Long.class, "remoteId", false, "REMOTE_ID");
        public final static Property LayoutType = new Property(2, String.class, "layoutType", false, "LAYOUT_TYPE");
        public final static Property Tags = new Property(3, String.class, "tags", false, "TAGS");
        public final static Property DeckId = new Property(4, long.class, "deckId", false, "DECK_ID");
    }

    ;

    private DaoSession daoSession;

    private Query<DBCard> dBDeck_CardsQuery;

    public DBCardDao(DaoConfig config) {
        super(config);
    }

    public DBCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'DBCARD' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'REMOTE_ID' INTEGER UNIQUE ," + // 1: remoteId
                "'LAYOUT_TYPE' TEXT NOT NULL ," + // 2: layoutType
                "'TAGS' TEXT," + // 3: tags
                "'DECK_ID' INTEGER NOT NULL );"); // 4: deckId
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBCARD'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBCard entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Long remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindLong(2, remoteId);
        }
        stmt.bindString(3, entity.getLayoutType());

        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(4, tags);
        }
        stmt.bindLong(5, entity.getDeckId());
    }

    @Override
    protected void attachEntity(DBCard entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public DBCard readEntity(Cursor cursor, int offset) {
        DBCard entity = new DBCard( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // remoteId
                cursor.getString(offset + 2), // layoutType
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tags
                cursor.getLong(offset + 4) // deckId
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, DBCard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemoteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLayoutType(cursor.getString(offset + 2));
        entity.setTags(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDeckId(cursor.getLong(offset + 4));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(DBCard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(DBCard entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Internal query to resolve the "cards" to-many relationship of DBDeck.
     */
    public List<DBCard> _queryDBDeck_Cards(long deckId) {
        synchronized (this) {
            if (dBDeck_CardsQuery == null) {
                QueryBuilder<DBCard> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DeckId.eq(null));
                dBDeck_CardsQuery = queryBuilder.build();
            }
        }
        Query<DBCard> query = dBDeck_CardsQuery.forCurrentThread();
        query.setParameter(0, deckId);
        return query.list();
    }

}
