package com.raulvintila.app.lieflashcards.Database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBCARD.
 */
public class DBCard {

    private Long remoteId;
    /** Not-null value. */
    private String layoutType;
    private String tags;
    private long deckId;
    private Long id;

    public DBCard() {
    }

    public DBCard(Long id) {
        this.id = id;
    }

    public DBCard(Long remoteId, String layoutType, String tags, long deckId, Long id) {
        this.remoteId = remoteId;
        this.layoutType = layoutType;
        this.tags = tags;
        this.deckId = deckId;
        this.id = id;
    }

    public Long getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(Long remoteId) {
        this.remoteId = remoteId;
    }

    /** Not-null value. */
    public String getLayoutType() {
        return layoutType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLayoutType(String layoutType) {
        this.layoutType = layoutType;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public long getDeckId() {
        return deckId;
    }

    public void setDeckId(long deckId) {
        this.deckId = deckId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
