package com.raulvintila.app.lieflashcards.Database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBDECK_TAG.
 */
public class DBDeckTag {

    private Long id;
    /** Not-null value. */
    private String text;
    private long deckId;

    public DBDeckTag() {
    }

    public DBDeckTag(Long id) {
        this.id = id;
    }

    public DBDeckTag(Long id, String text, long deckId) {
        this.id = id;
        this.text = text;
        this.deckId = deckId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public long getDeckId() {
        return deckId;
    }

    public void setDeckId(long deckId) {
        this.deckId = deckId;
    }

}
