package com.raulvintila.app.lieflashcards.Database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBVOTE.
 */
public class DBVote {

    private Long id;
    private Long remoteId;
    private int rating;
    private String message;
    private Long datePosted;
    private long deckId;

    public DBVote() {
    }

    public DBVote(Long id) {
        this.id = id;
    }

    public DBVote(Long id, Long remoteId, int rating, String message, Long datePosted, long deckId) {
        this.id = id;
        this.remoteId = remoteId;
        this.rating = rating;
        this.message = message;
        this.datePosted = datePosted;
        this.deckId = deckId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRemoteId() {
        return remoteId;
    }

    public void setRemoteId(Long remoteId) {
        this.remoteId = remoteId;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getDatePosted() {
        return datePosted;
    }

    public void setDatePosted(Long datePosted) {
        this.datePosted = datePosted;
    }

    public long getDeckId() {
        return deckId;
    }

    public void setDeckId(long deckId) {
        this.deckId = deckId;
    }

}
