package com.raulvintila.app.lieflashcards.Database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table DBVOTE.
*/
public class DBVoteDao extends AbstractDao<DBVote, Long> {

    public static final String TABLENAME = "DBVOTE";

    /**
     * Properties of entity DBVote.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemoteId = new Property(1, Long.class, "remoteId", false, "REMOTE_ID");
        public final static Property Rating = new Property(2, int.class, "rating", false, "RATING");
        public final static Property Message = new Property(3, String.class, "message", false, "MESSAGE");
        public final static Property DatePosted = new Property(4, Long.class, "datePosted", false, "DATE_POSTED");
        public final static Property DeckId = new Property(5, long.class, "deckId", false, "DECK_ID");
    };

    private Query<DBVote> dBDeck_VotesQuery;

    public DBVoteDao(DaoConfig config) {
        super(config);
    }
    
    public DBVoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DBVOTE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'REMOTE_ID' INTEGER UNIQUE ," + // 1: remoteId
                "'RATING' INTEGER NOT NULL ," + // 2: rating
                "'MESSAGE' TEXT," + // 3: message
                "'DATE_POSTED' INTEGER," + // 4: datePosted
                "'DECK_ID' INTEGER NOT NULL );"); // 5: deckId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBVOTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBVote entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindLong(2, remoteId);
        }
        stmt.bindLong(3, entity.getRating());
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(4, message);
        }
 
        Long datePosted = entity.getDatePosted();
        if (datePosted != null) {
            stmt.bindLong(5, datePosted);
        }
        stmt.bindLong(6, entity.getDeckId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBVote readEntity(Cursor cursor, int offset) {
        DBVote entity = new DBVote( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // remoteId
            cursor.getInt(offset + 2), // rating
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // message
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // datePosted
            cursor.getLong(offset + 5) // deckId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBVote entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemoteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRating(cursor.getInt(offset + 2));
        entity.setMessage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDatePosted(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDeckId(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBVote entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBVote entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "votes" to-many relationship of DBDeck. */
    public List<DBVote> _queryDBDeck_Votes(long deckId) {
        synchronized (this) {
            if (dBDeck_VotesQuery == null) {
                QueryBuilder<DBVote> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DeckId.eq(null));
                dBDeck_VotesQuery = queryBuilder.build();
            }
        }
        Query<DBVote> query = dBDeck_VotesQuery.forCurrentThread();
        query.setParameter(0, deckId);
        return query.list();
    }

}
